# When /annihilation start is run, the delay before starting phase 1 in seconds
start-delay: 40
#
# Phase length in seconds (Phase 5 is perpetual)
phase-period: 600
#
# When the game ends, the delay before resetting the game
restart-delay: 20

# Kolik budou stat kity (ne CLASSIC)
kit-cost: 200

#
# Stat system: "flatfile" for yml or "sql" for MySQL
stats: flatfile
#
MySQL:
    port: 3306
    user: username
    pass: password
    host: host
    name: annihilation
#   
# Display Roman Numerals for phase numbers
roman: true
#
# Auto updater
allowUpdater: true
#
# Amount of players required to start the game
requiredToStart: 2
#
# Build Distance from Nexus
build: 15
#
# Delay in minutes to respawn the bosses after death
bossRespawnDelay: 10
#
# Enable the custom MOTD
enableMotd: true
#
# The last phase players can join a team
lastJoinPhase: 2
#
# Custom MOTD - Values you can use
# %PHASE% %TIME% %PLAYERCOUNT% %MAXPLAYERS%
# %GREENNEXUS% %REDNEXUS% %BLUENEXUS% %YELLOWNEXUS%
# %GREENCOUNT% %REDCOUNT% %BLUECOUNT% %YELLOWCOUNT% 
motd: '&cPhase: &5%PHASE%'
motd-lobby: '&6Lobby'
motd-start: '&6Phase: &2%PHASE%'
#
# Un-comment the below to enable
# NOTICE: If enabled the game WILL NOT AUTO RESTART.
commandsToRunAtEndGame:
 - "wr reset now"
#
#Economy setup
Exp-player-kill: 100
Exp-boss-kill: 400
Money-nexus-hit: 0
Money-nexus-kill: 0
Money-player-kill: 0
Money-boss-kill: 0
Money-win: 200
#
Chat:
  no-team:
  team:
  all-team:
#
#Ending game
Force-end:
  hours: 1
  minutes: 30
#Boss loot settings
Boss-loot:
  Item-Nb: 7
  Item0:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_HELMET
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 1
        OXYGEN: 3
      display-name: 'Oxyger'
      lore:
      - 'Power of oxygen'
      - 'Unique Item'
      repair-cost: 4
  Item1:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_HELMET
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
        OXYGEN: 3
      display-name: 'Oxyger II'
      lore:
      - 'Power of oxygen II'
      - 'Rare Item'
      repair-cost: 4
  Item2:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_LEGGINGS
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
      display-name: 'Anti sharp'
      lore:
      - 'Better than normal.'
      - 'Unique Item'
      repair-cost: 2
  Item3:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_BOOTS
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 2
        PROTECTION_FALL: 4
      display-name: 'Fly boots'
      lore:
      - 'Less damage of falling.'
      - 'Rare Item'
      repair-cost: 2
  Item4:
    ==: org.bukkit.inventory.ItemStack
    type: BOW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        ARROW_INFINITE: 1
      display-name: 'Infinite Shooter'
      lore:
      - 'This bow is great.'
      - 'Unique Item'
      repair-cost: 4
  Item5:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        DAMAGE_ALL: 3
      display-name: 'Blood finder'
      lore:
      - 'Sharpness is your brother.'
      - 'Unique Item'
      repair-cost: 2
  Item6:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_CHESTPLATE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        PROTECTION_ENVIRONMENTAL: 4
      display-name: 'Troll plate'
      lore:
      - 'Defending is smarter'
      - 'Unique Item'
      repair-cost: 2